[[main]]
name = "Hakkımda"
url = "/#about"
weight = 2

[[main]]
name = "Yetenekler"
url = "/#skills"
weight = 3

[[main]]
name = "Deneyimler"
url = "/#experience"
weight = 4

[[main]]
name = "Tech Stack"
url = "/#technical"
weight = 5
	  
[[main]]
name = "İletişim"
url = "/#contact"
weight = 6

[[main]]
name = "AI"
url = "/ai/"
weight = 45

[[main]]
name = "Yazılım"
url = "/software/"
weight = 46  

[[main]]
name = "Blog"
url = "/blog/"
weight = 60  